project:
  type: book

book:
  title: "Advanced Data Science for Public Health"
  author: "Brian Caffo"
  date: "7/7/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - graphics.qmd
    - interactive.qmd
    - webscraping.qmd
    - databases.qmd
    - pipelines.qmd
    - data_structures.qmd
    - diymlai.qmd
    - nlp.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



