project:
  type: book

book:
  repo-url: https://github.com/smart-stats/advanced_ds4bio_book
  title: "Advanced Data Science for Public Health"
  author: "Brian Caffo"
  date: "7/7/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - interactive.qmd
    - webscraping.qmd
    - images.qmd
    - databases.qmd
    - pipelines.qmd
    - data_structures.qmd
    - diymlai.qmd
    - convnet_example.qmd
    - unsupervised.qmd
    - variationalAEs.qmd
    - nlp.qmd
    - data_analysis_theory.qmd
    - stat_language.qmd
    - data_science_as_a_science.qmd
    - graphics.qmd
    - causal.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



