---
title: "Theory of graphical display"
format: html
---

## Design arguments 
One of the main design arguments for the graphical display of information is data / ink maximization @tufte1990data. This is the idea that idea that as much of the "ink" (non-background pixels) of the plot as possible should be displaying data. 

Data/ink maximalization has been criticized empirically. For example, @inbar2007minimalism conducted a study with 87 undergraduates and found a clear preference for the non-maximized variations. Another line of argument discusses the "paradox of simplicity" @norman2007simplicity, @eytam2017paradox, whereby we have a strong aesthetic preference for simplicity, but also want flexibility and maximum utility.

+ @bertin1983semiology

### Graphical critique
+ @wickham2010graphical

### Theory of graphics



+ @cleveland1987research
+ @cleveland1984many
+ @cleveland1980calendar
+ @carswell1992choosing
+ @cleveland1986experiment
+ Magical thinking @diaconis2006theories

## Implementation 
### Grammar of graphics
+ @wilkinson2012grammar
+ @wilkinson2013grammar
+ @wickham2010layered

### Narative storytelling
Edward and Jeffrey (@segel2010narrative) argue regarding the use of modern interactive tools in data narrative storytelling. They give seven canonical genres of narrative visulation.



## Historical graphics

## Graph galleries

